apiVersion: apps/v1
kind: Deployment
metadata:
  name: atehere-deployment
  namespace: dorduncuboyut
spec:
  selector:
    matchLabels:
      app: atehere

  template:
    metadata:
      labels:
        app: atehere

    spec:
      containers:
        - name: atehere
          image: ghcr.io/mechatron-x/atehere:release
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          command: ["atehere"]
          args: ["-c", "/etc/atehere/application.json"]
          envFrom:
            - secretRef:
                name: atehere-db-secret
            - secretRef:
                name: atehere-firebase-secret
          volumeMounts:
            - name: config-volume
              mountPath: /etc/atehere
            - name: static-volume
              mountPath: /var/lib/atehere/static
          ports:
            - name: web
              containerPort: 80
          imagePullPolicy: Always

        - name: atehere-db
          image: docker.io/postgres:17-bookworm
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - secretRef:
                name: atehere-db-secret
          volumeMounts:
            - name: pg-volume
              mountPath: /var/lib/postgresql/data
          ports:
            - containerPort: 5432
          imagePullPolicy: Always

      imagePullSecrets:
        - name: mechatron-x.ghcr.io

      volumes:
        - name: config-volume
          configMap:
            name: atehere-appconfig
            items:
              - key: application.json
                path: application.json
        - name: pg-volume
          nfs:
            server: pi-manager-1
            path: /shared/atehere/data
            readOnly: false
        - name: static-volume
          nfs:
            server: pi-manager-1
            path: /shared/atehere/static
            readOnly: false
