apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: atehere-ingress
  namespace: dorduncuboyut
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"

spec:
  rules:
    - host: dorduncuboyut.media
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: atehere-service
                port:
                  number: 80
  tls:
    - secretName: dorduncuboyut.media.certs