apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atehere-db-pvc
  namespace: codebrewlab-live
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atehere-static-pvc
  namespace: codebrewlab-live
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn 
  resources:
    requests:
      storage: 20Gi
